### ISSUE TITLE
Gulp - Minifying CSS breaks Sass to Css conversion

### ISSUE THREAD

**Issue by Gheard21** [Gheard21/week_5_website_project#18]
`/* 
gulp.task('minify-css', () => {
    return gulp.src('./dest/css/*.css')
        .pipe(cleanCss())
        .pipe(gulp.dest('./dest/css/'))
})*/

gulp.task('watching', () => {
    gulp.watch('./src/sass/*', ['sass-transform'])
    // gulp.watch('./dest/css/main.css', ['minify-css'])
})`

**Comment by AnjanaRao1987** [comment]
Done
